/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package randomQuotes;

import org.junit.Test;

import java.io.FileNotFoundException;

import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testRandomQuote_pass() throws FileNotFoundException {
        App classUnderTest = new App();
        User expectedOutput = classUnderTest.randomQuote("src/main/resources/quoteData.txt");
        assertNotNull("should return random user quote", expectedOutput);
    }

    @Test (expected = FileNotFoundException.class)
    public void testRandomQuote_expectFailBadPath() throws FileNotFoundException{
        App classUnderTest = new App();
        assertNull("should fail",classUnderTest.randomQuote("../resources/quoteData.txt"));
    }

    //throw bad filename into function
}
