/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package randomQuotes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;


import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.Random;


public class App {

    public static void main(String[] args) {

        System.out.println(randomQuote());
//        System.out.println(randomQuoteFile());

    }


    public static String randomQuote(){
        try{
            //get url and pass to reader
            URL url = new URL("https://got-quotes.herokuapp.com/quotes");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            BufferedReader reader = new BufferedReader(new InputStreamReader(con.getInputStream()));

            //convert data to gson
            Gson iGson = new Gson();
            User gotQuote = iGson.fromJson(reader, User.class);

            //convert quote to json object
            User newQuote = new User(gotQuote.getCharacter(), gotQuote.getQuote());
            String gotQuoteToJSON = iGson.toJson(newQuote);


            //read && write file
            writeFile(readFile(newQuote));

            return gotQuote.toString_GoT();

        } catch (Exception e){
            System.out.println(e);
            return randomQuoteFile();
        }
    }

    public static ArrayList readFile(User user){
        try{
            Gson gson = new Gson();
            JsonReader oldFile = new JsonReader(new FileReader("src/main/resources/quoteData.txt"));
            ArrayList<User> quotes = new ArrayList<>();
            oldFile.beginArray();
            while(oldFile.hasNext()){
                User quote = gson.fromJson(oldFile, User.class);
                quotes.add(quote);
            }
            quotes.add(user);
            oldFile.endArray();
            oldFile.close();
            return quotes;
        } catch (IOException e){
            System.out.println(e);
            return new ArrayList();
        }
    }

    public static void writeFile(ArrayList<User> arr){
        try {
            Gson gson = new Gson();
            JsonWriter writer = new JsonWriter(new FileWriter("src/main/resources/quoteData.txt"));
            writer.setIndent("  ");
            writer.beginArray();
            for(User quote: arr){
                gson.toJson(quote, User.class, writer);
            }
            writer.endArray();
            writer.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }

    public static String randomQuoteFile(){
        try {
            Gson gson = new GsonBuilder().setPrettyPrinting().create();

            BufferedReader bufferedReader = new BufferedReader(new FileReader("src/main/resources/quoteData.txt"));

            User[] users = gson.fromJson(bufferedReader, User[].class);

            return users[randomNumber(users)].toString();
        } catch (FileNotFoundException err){
            System.out.println(err);
            User user = new User("House Stark", "Winter is coming");
            return user.toString_GoT();
        }
    }

    public static int randomNumber(User[] arr){
        Random rand = new Random();
        int i = rand.nextInt(arr.length);
        return i;
    }
}
